agents:
  underbilling_agent:
    role_env: UNDERBILLING_USER
    password_env: UNDERBILLING_PASSWORD
    tables:
      timecard:
        - "timecard_id"
        - "timekeeper_id"
        - "matter_id"
        - "date"
        - "worked_hours"
        - "worked_rate"
        - "worked_amount"
        - "standard_rate"
        - "standard_amount"
        - "is_nonbillable"
        - "is_no_charge"
        - "is_active"
      matter_timekeeper_summary:
        - "tk_mat_sum_id"
        - "matter_id"
        - "timekeeper_id"
        - "year"
        - "worked_hours"
        - "worked_amount"
        - "standard_amount"
        - "is_error"
        - "error_message"
      timekeeper:
        - "timekeeper_id"
        - "timekeeper_name"
        - "type"
        - "attribute"
        - "category"
        - "is_active"
        - "is_current"
        - "is_error"
        - "error_message"
      matter:
        - "matter_id"
        - "matter_name"
        - "client_id"
        - "type"
        - "rate_set_id"
        - "is_active"
        - "is_current"
      client:
        - "client_id"
        - "client_name"
        - "rate_set_id"
        - "is_active"
        - "is_current"
      rate_set:
        - "rate_set_id"
        - "rate_set_code"
        - "rate_set_name"
      rate_set_link:
        - "rate_set_link_id"
        - "rate_set_id"
        - "rate_component_id"
        - "rate_type"
      rate_component:
        - "rate_component_id"
        - "rate_type"
        - "start_date"
        - "end_date"
      rate_detail:
        - "rate_detail_id"
        - "rate_component_id"
        - "rate_amount"
        - "deviation_amount"
        - "deviation_percent"
        - "start_date"
        - "end_date"
  profitability_agent:
    role_env: PROFITABILITY_USER
    password_env: PROFITABILITY_PASSWORD
    tables:
      timecard:
        - "timecard_id"
        - "timekeeper_id"
        - "matter_id"
        - "date"
        - "worked_hours"
        - "worked_rate"
        - "worked_amount"
        - "standard_rate"
        - "standard_amount"
        - "is_nonbillable"
        - "is_no_charge"
        - "is_active"
      matter_timekeeper_summary:
        - "tk_mat_sum_id"
        - "matter_id"
        - "timekeeper_id"
        - "year"
        - "worked_hours"
        - "worked_amount"
        - "standard_amount"
        - "is_error"
        - "error_message"
      timekeeper:
        - "timekeeper_id"
        - "timekeeper_name"
        - "type"
        - "attribute"
        - "category"
        - "cost_rate"
        - "is_active"
        - "is_current"
        - "is_error"
        - "error_message"
      matter:
        - "matter_id"
        - "matter_name"
        - "client_id"
        - "type"
        - "rate_set_id"
        - "is_active"
        - "is_current"
      client:
        - "client_id"
        - "client_name"
        - "rate_set_id"
        - "is_active"
        - "is_current"
      rate_set:
        - "rate_set_id"
        - "rate_set_code"
        - "rate_set_name"
      rate_set_link:
        - "rate_set_link_id"
        - "rate_set_id"
        - "rate_component_id"
        - "rate_type"
      rate_component:
        - "rate_component_id"
        - "rate_type"
        - "start_date"
        - "end_date"
      rate_detail:
        - "rate_detail_id"
        - "rate_component_id"
        - "rate_amount"
        - "deviation_amount"
        - "deviation_percent"
        - "start_date"
        - "end_date"