agents:
  underbilling_agent:
    role_env: UNDERBILLING_USER
    password_env: UNDERBILLING_PASSWORD
    tables:
      legal_billing:
        - "Timekeeper ID"
        - "Timekeeper Name"
        - "Timekeeper Role"
        - "Standard Rate"
        - "Work Rate"
        - "Matter ID"
        - "Matter Name"
        - "Matter Type"
        - "Client ID"
        - "Client Name"
        - "Invoice Date"
        - "Billed Hours"
        - "Billed Amount"
        - "Collected Hours"
        - "Collected Amount"
        - "Write Off Amount"
        - "Discount Amount"
        - "Realization Rate"
        - "Utilization Rate"
        - "Worked Hours"
        - "Worked Amount"
        - "Effective Rate"
        - "Time Entry Date"
        - "Time Entry Hours"
        - "Time Entry Description"
        - "Underbilling Flag"
        - "Discount Flag"
      timekeeper_details:
        - "Timekeeper ID"
        - "Timekeeper Status"
        - "Timekeeper Office"
        - "Timekeeper Department"

  profitability_agent:
    role_env: PROFITABILITY_USER
    password_env: PROFITABILITY_PASSWORD
    tables:
      legal_billing:
        - "Timekeeper ID"
        - "Matter ID"
        - "Matter Name"
        - "Matter Type"
        - "Matter Status"
        - "Matter Office"
        - "Matter Department"
        - "Matter Practice Group"
        - "Billing Attorney"
        - "Supervising Attorney"
        - "Responsible Attorney"
        - "Originating Attorney"
        - "Budget"
        - "Target"
        - "Client ID"
        - "Client Name"
        - "Client Address"
        - "Client Status"
        - "Client Type"
        - "Invoice ID"
        - "Invoice Date"
        - "Billed Hours"
        - "Billed Amount"
        - "Collected Hours"
        - "Collected Amount"
        - "Write Off Amount"
        - "Discount Amount"
        - "Realization Rate"
        - "Utilization Rate"
        - "Worked Hours"
        - "Worked Amount"
        - "Effective Rate"
        - "Flat Fee Amount"
        - "Trust Balance"
        - "WIP Amount"
        - "AR Amount"
        - "Soft Costs"
        - "Hard Costs"
        - "Phase Code"
        - "Task Code"
        - "Activity Code"
        - "Time Entry Date"
        - "Time Entry Hours"
      timekeeper_details:
        - "Timekeeper ID"
        - "Timekeeper Name"
        - "Timekeeper Role"
        - "Timekeeper Status"
        - "Timekeeper Office"
        - "Timekeeper Department"
        - "Timekeeper Practice Group"